[env]
COMPOSE_FILE = "{{config_root}}/.dev/docker-compose.yml"
GID = 1000

[tasks.nvim]
description = "Connect to Neovim in the container."
run = "nvim --remote-ui --server localhost:7777"
alias = "n"

[tasks.guard]
description = "Start the Guard runner."
run = "docker-compose run --rm -it app bundle exec guard"

[tasks.rails]
description = "Enter the running Rails container."
run = "docker-compose exec app /bin/zsh"

[tools]
ruby = "3.2.3"
